trigger: 
- main

pool: 
   vmImage: BROTE

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: fi-postgres-dev
   resourceName: fi-postgres-dev
   resourceType: virtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"