trigger: 
- main

pool: Default

# variables:
POSTGRES_HOST: $(POSTGRES_HOST)
POSTGRES_DB: $(POSTGRES_DB)
POSTGRES_USER: $(POSTGRES_USER)

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'brote-dev-001'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      ACCESS_TOKEN=$(az account get-access-token --resource=https://ossrdbms-aad.database.windows.net --query 'accessToken' -o tsv)
      echo "##vso[task.setvariable variable=ACCESS_TOKEN]$ACCESS_TOKEN"
  displayName: 'Fetch Access Token'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
    export POSTGRES_HOST=$(POSTGRES_HOST)
    export POSTGRES_DB=$(POSTGRES_DB)
    export POSTGRES_USER=$(POSTGRES_USER)
  env:
    ACCESS_TOKEN: $(ACCESS_TOKEN)
  displayName: 'pytest'