trigger: 
- main

pool: 
   vmImage: BROTE

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: fi-postgres-dev
   resourceName: BROTE
   resourceType: virtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
- job: 'Test'
  displayName: python-versions
  strategy:
   matrix:
      Python38:
         'python.version': '3.8'
      Python39:
         'python.version': '3.9'
      Python310:
         'python.version': '3.10'
   
   steps:
   - task: UsePythonVersion@0
     inputs:
      versionSpec: '$(python.version)'