trigger: 
- main

pool: 
   vmImage: build-agent

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: fi-postgres-dev
    resourceType: virtualMachine
    resourceName: BROTE # only deploy to the VM resource named BROTE
  strategy:
      runOnce:
         deploy:
            steps:
            - task: UsePythonVersion@0
              inputs:
                versionSpec: '3.8'
                disableDownloadFromRegistry: true
                addToPath: true
                architecture: 'x64'

            - script: pip install -r requirements.txt
              displayName: 'Install dependencies'

            - script: python -m unittest discover
              displayName: 'Run tests'
