trigger: 
- main

pool: Default

variables:
  POSTGRES_HOST: $(POSTGRES_HOST)
  POSTGRES_DB: $(POSTGRES_DB)
  POSTGRES_USER: $(POSTGRES_USER)

strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    # Fetch the token
    ACCESS_TOKEN=$(az account get-access-token --resource=https://ossrdbms-aad.database.windows.net)

- script: |
    pip install pytest pytest-azurepipelines
    # export POSTGRES_HOST=$(POSTGRES_HOST)
    # export POSTGRES_DB=$(POSTGRES_DB)
    # export POSTGRES_USER=$(POSTGRES_USER)
    # export ACCESS_TOKEN=$(ACCESS_TOKEN)
    pytest
  displayName: 'pytest'